yodaos-project/ShadowNode

src/js/fs.js
src/js/stream_readable.js

Add the following `fs` module functions:
- `fs.createReadStream()`
- `fs.createWriteStream()`

fs: add ReadStream and WriteStream

---

src/js/http_incoming.js

Just corrects the http headers on incoming message!

http: fix the header names

---

src/js/http.js
src/js/http_agent.js
src/js/https.js
src/js/os.js
src/modules.json
src/modules/iotjs_module_os.c

Support urllib for HTTP requests(#2).

http, https: add Agent and os.release() to support urllib

---

src/modules/iotjs_module_zlib.c

zlib: check status throws error

---

deps/libtuv/cmake/option/option_unix_common.cmake
deps/libtuv/src/unix/core.c
deps/libtuv/src/unix/signal.c
src/js/child_process.js
src/js/net.js
src/modules.json
src/modules/iotjs_module_child_process.c
src/modules/iotjs_module_pipe.c
src/modules/iotjs_module_pipe.h

Currently it only supports spawn() without IPC, and not supports fork() and exec().
/cc @maxbbn

child_process: this module is working now

---

src/js/child_process.js

child_process: fix the close event to be emitted

---

src/js/child_process.js
src/js/net.js

```js
var exec = require('child_process').exec;
exec('cat *.js bad_file | wc -l', function(error, stdout, stderr) {
if (error) {
console.error('exec error: ' + error);
return;
}
console.log('stdout: ' + stdout);
console.log('stderr: ' + stderr);
});
```
The above code is working now :)

child_process: add .exec()

---

src/js/buffer.js
src/js/util.js

Changes:
- fix the JSON replacer for Buffer
- add the Buffer.prototype.inspect
This patch is plan to merge into upstream.

util: improve format object

---

src/js/stream.js
src/js/stream_passthrough.js
src/modules.json
src/modules/iotjs_module_https.c
src/modules/iotjs_module_zlib.c

This supports #2 for node-fetch, but notice that, don't use `compress` option for now :(

stream, zlib: support node-fetch

---

src/js/fs.js

This completely supports lowdb for #2 :)

fs: add options to fs.read and fs.write

---

src/js/dbus.js

This patch keeps consistent with node-dbus library :)

dbus: add .Define method()

---

src/js/mqtt.js
src/js/stream_readable.js
src/js/tls.js
src/modules.json
src/modules/iotjs_module_crypto.c
src/modules/iotjs_module_crypto.h
src/modules/iotjs_module_mqtt.c
src/modules/iotjs_module_tls.c

tls: initialized the "TLS" module based on mbedtls

---

cmake/iotjs.cmake
samples/addon/CMakeLists.txt
samples/addon/binding.c

This install the headers(iotjs/jerry/uv) `${INSTALL_PREFIX}/include/shadow-node/` :)

build: install iotjs/jerry/uv headers

---

src/js/iotjs.js

polyfill shall be loaded before any core modules been required

fix(iotjs): failed to load console.js

---

src/js/iotjs.js

iotjs: move the uncaught handler to front

---

.travis.yml
src/modules/iotjs_module_crypto_hash.c
src/modules/iotjs_module_tls.c

This closes #64.
/cc @legendecas

tls, crypto: fix some memory leak

---

src/js/https_client.js
test/run_pass/test_net_https_get.js

https: fix request callback not called

---

src/js/https_client.js
src/js/websocket.js

Add `wss://` and `https://` supports for WebSocket.

websocket: add socket

---

src/js/module.js

Adds the parent's route paths to search dirs.
Refs: https://nodejs.org/dist/latest-v9.x/docs/api/modules.html

module: follow the LOAD_NODE_MODULES() algorithm from Node.js official

---

src/modules/iotjs_module_websocket.c

websocket: fix the mem length

---

src/modules/iotjs_module_child_process.c

Fix some invalid writes to memory detected by valgrind :)

child_process: fix the invalid write to memory

---

src/js/websocket.js

Throw an error when received invalid message :)

ws: throw utf invalid error when received message

---

src/js/child_process.js
test/run_pass/test_child_process_kill.js
test/run_pass/test_child_process_kill2.js
test/testsets.json
tools/test_runner.js

child_process: fix kill signal

---

src/iotjs.c

This patch is pulled from upstream updates.

iotjs: checking default uvloop value

---

src/js/dbus.js

This fixes the method calling with arguments.
/cc @LanFly

dbus: fix the missing arguments

---

deps/jerry/jerry-core/ecma/base/ecma-helpers-string.c
deps/jerry/tests/unit-core/test-api.c

#ref https://github.com/jerryscript-project/jerryscript/pull/2261
Closing #96

fix: accessing the contents of a direct string

---

src/iotjs.c
src/iotjs_magic_strings.h
src/modules/iotjs_module_process.c
test/crash/exit-failure.js
test/crash/exit-ok.js
test/crash/exit-with-exception.js
test/crash/signal-segv.js
tools/build.py
tools/check_crash.sh

To test the case, added a kill method to monitor the segv/... signal.

iotjs: handle segv and exit event, remove dump file when exiting.

---

.travis.yml

Sorry #157 deletes this lint check, just re-add it.
/cc @algebrait @legendecas

travis: run lint before travis scripts

---

src/iotjs.c

fix: disable stdio buffering for poorly interacting with printf

---

src/modules/iotjs_module_dbus.c

The signal emits doesn't get supported for multiple arguments.

dbus: support multiple arguments for signal emits

---

src/js/dbus.js

dbus: should throw better message when caller is invalid

---

tools/profiler/cl.py

profiler: record filename if no function name and line info provided

---

src/js/module.js
test/run_pass/require1/arbitrary_file.txt
test/run_pass/test_module_require.js

module: any unknown extensions shall be treated as js

---

.travis.yml
cmake/jerry.cmake
src/iotjs.c
tools/build.py
tools/travis_script.py

cmake: add jerryx dependency to iotjs

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Hey @Rokid/nodejs guys, let's add these templates right now!

github: add pull request and issue template which follow nodejs

---

benchmark/json/stringify-nested.js
benchmark/json/stringify-string.js
benchmark/json/stringify.js

Unit: operations per second
| Build | Flat Object | Deeply Nested Object | Flat String |
| --- | --- | --- | --- |
| Before #250  | 18.12 | 5.38 | 13.37
| With #250 | 21.28 | 6.99 | 20.01
| Node.js v10.8.0 | 5,599.00 | 3,468.19 | 6,377.46

benchmark: json.stringify

---

tools/testrunner.py

tools: test runner shall exit with non-zero code if fail

---

.gitignore
src/js/iotjs.js
test/run_pass/require2/node_modules/foobar/index.js
test/run_pass/test_module_require2.js
test/testsets.json
tools/testrunner.py

The `module` uses the `process.env.NODE_ENV` before it gets setup, this just moves the function `setupEnviron()` in head of the bootstrap file.

module: fix NODE_MODULE environment works

---

src/internal/node_api_internal.h
src/internal/node_api_internal_types.h
src/napi/node_api_env.c
src/napi/node_api_function.c
src/napi/node_api_module.c
src/napi/node_api_property.c
src/napi/node_api_value.c
test/napi/napi.test.c
test/napi/napi.test.js

depends on #256 
N-API methods implemented in this PR:
- Error Handling
- Return values
- napi_get_last_error_info
- Exceptions
- napi_throw
- napi_throw_error
- napi_throw_type_error
- napi_throw_range_error
- napi_get_and_clear_last_exception
- napi_is_exception_pending
- Working with JavaScript Values
- Functions to convert from C types to N-API
- napi_create_int32
- napi_create_uint32
- napi_create_int64
- napi_create_double
- napi_create_string_utf8
- Functions to convert from N-API to C types
- napi_get_value_double
- napi_get_value_int32
- napi_get_value_int64
- napi_get_value_uint32
- Working with JavaScript Properties
- Functions
- napi_set_named_property
- Working with JavaScript Functions
- napi_create_function

napi: env and functions

---

src/internal/node_api_internal.h
src/napi/node_api_property.c

Working with JavaScript Properties
- napi_get_property_names
- napi_set_property
- napi_get_property
- napi_has_property
- napi_delete_property
- napi_has_own_property
- napi_get_named_property
- napi_has_named_property
- napi_set_element
- napi_get_element
- napi_has_element
- napi_delete_element
- napi_define_properties

napi: working with javascript properties

---

src/internal/node_api_internal.h
src/napi/node_api_lifetime.c

Making handle lifespan shorter than that of the native method
- napi_open_handle_scope
- napi_close_handle_scope
- napi_open_escapable_handle_scope
- napi_close_escapable_handle_scope
- napi_escape_handle

napi: handle scopes management

---

src/internal/node_api_internal.h
src/napi/node_api_function.c

- napi_call_function
- napi_get_cb_info
- napi_new_instance

napi: function operations

---

src/internal/node_api_internal.h
src/internal/node_api_internal_types.h
src/napi/node_api_function.c
src/napi/node_api_lifetime.c
src/napi/node_api_object_wrap.c
src/napi/node_api_property.c

References to objects with a lifespan longer than that of the native method
- napi_create_reference
- napi_delete_reference
- napi_reference_ref
- napi_reference_unref
- napi_get_reference_value
Object Wrap
- napi_define_class
- napi_wrap
- napi_unwrap
- napi_remove_wrap

napi: object native info

---

deps/jerry/jerry-core/api/jerry.c
deps/jerry/jerry-core/include/jerryscript-core.h
src/internal/node_api_internal.h
src/napi/node_api_env.c
src/napi/node_api_function.c
src/napi/node_api_value.c
test/napi/napi.test.c
test/napi/napi.test.js

N-API methods implemented in this PR:
- napi_create_error
- napi_create_type_error
- napi_create_range_error
- napi_instanceof
- napi_strict_equals
Fixes not clearing handled last thrown error.

napi: object abstract operations

---

src/napi/node_api_function.c
test/napi/napi.test.c

Though it's not clear if out arguments could be NULL in N-API documents, cases shall be considered and not crash the program.

napi: napi_get_cb_info shall accepts NULL pointers

---

.travis.yml
test/node/parallel/test-http-abort.js
tools/apt-get-install-deps.sh
tools/travis_script.py

ci: clean up dependencies

---

docs/api/Assert.md
src/js/assert.js
src/js/util.js
test/run_pass/test_assert.js

assert: assert.throws expectation

---

src/napi/node_api_value.c

- napi_create_external
- napi_get_value_external
- napi_get_value_string_utf8

napi: external object

---

docs/api/Assert.md
src/js/assert.js
test/run_pass/test_assert.js
test/run_pass/test_fs_mkdir_rmdir.js
test/run_pass/test_fs_stat.js
test/run_pass/test_fs_write.js
test/run_pass/test_net_http_request_response.js
test/run_pass/test_net_https_post_status_codes.js
test/run_pass/test_spi.js

assert: assert.ok

---

deps/jerry/jerry-ext/handle-scope/handle-scope-internal.h
deps/jerry/jerry-ext/handle-scope/handle-scope.c
deps/jerry/jerry-ext/include/jerryscript-ext/handle-scope.h
src/internal/node_api_internal.h
src/internal/node_api_internal_types.h
src/napi/node_api_env.c
src/napi/node_api_function.c
src/napi/node_api_value.c
test/napi-testsets.json
test/napi/binding.gyp
test/napi/napi_arguments.c
test/napi/napi_arguments_return.test.js
test/napi/napi_arguments_return_this.test.js
test/napi/napi_arguments_throw.test.js
test/napi/napi_error.c
test/napi/napi_error_rethrow.test.js
test/napi/napi_error_throw.test.js
test/napi/napi_fatal_error.c
test/napi/napi_fatal_error_1.test.js
test/napi/napi_fatal_error_2.test.js

N-API methods included in this PR: 
- napi_fatal_error
Issues fixed in this PR:
- returning this in external function (test/napi/napi_arguments_return_this.test.js)
- throw scoped errors (test/addons-napi/test_handle_scope/test.js)

napi: exceptions

---

src/internal/node_api_internal.h
src/internal/node_api_internal_types.h
src/napi/node_api.c
src/napi/node_api_async.c
src/napi/node_api_function.c
src/napi/node_api_lifetime.c
src/napi/node_api_object_wrap.c
src/napi/node_api_value.c
test/common/index.js
test/napi-testsets.json
test/napi/binding.gyp
test/napi/napi_async.cc
test/napi/napi_async.test.js
test/napi/napi_reference.c
test/napi/napi_reference.test.js

- napi_get_uv_event_loop
- napi_create_async_work
- napi_delete_async_work
- napi_queue_async_work
- napi_cancel_async_work

napi: simple async operations

---

deps/jerry/jerry-ext/handle-scope/handle-scope-allocator.c
deps/jerry/tests/unit-ext/test-ext-handle-scope-nested.c
test/napi-testsets.json
test/napi/binding.gyp
test/napi/napi.test.js
test/napi/napi_arguments_return.test.js
test/napi/napi_arguments_return_this.test.js
test/napi/napi_arguments_throw.test.js
test/napi/napi_async.test.js
test/napi/napi_construct.c
test/napi/napi_construct.test.js
test/napi/napi_error_rethrow.test.js
test/napi/napi_error_throw.test.js
test/napi/napi_fatal_error_1.test.js
test/napi/napi_fatal_error_2.test.js
test/napi/napi_reference.test.js
test/napi/napi_string.test.js

fix: close handle scopes doesn’t reset current scope

---

.github/ISSUE_TEMPLATE/1-bug-report.md
.github/ISSUE_TEMPLATE/2-feature-request.md

Add issue template option list:

github: add issue template list

---

.eslintignore
src/internal/node_api_internal.h
src/modules/iotjs_module_process.c
src/napi/node_api_async.c
src/napi/node_api_env.c
src/napi/node_api_function.c
src/napi/node_api_module.c
test/common/index.js
test/napi/napi_error.c
test/napi/napi_error_rethrow.test.js
test/napi/napi_error_throw.test.js

fix: unhandled n-api error on module init

---

README.md
docs/api/N-API.md
docs/api/README.md

doc: n-api

---

README.md

Fixes the links to N-API docs at README.

doc: fix napi link at readme

---

src/js/util.js
test/run_pass/test_util_promisify.js
test/testsets.json

add util.promisify

---

CMakeLists.txt
package.json

In [v0.9.x](https://github.com/Rokid/ShadowNode/commits/v0.9.x), we mainly landed the basic N-API and pulls the test suites from official [nodejs/node](https://github.com/nodejs/node), check [N-API.md](https://github.com/Rokid/ShadowNode/blob/master/docs/api/N-API.md) for the complete documentation and compatible list.
Moreover, we tweaked the module search algorithm by following Node.js absolutely, and added an environment variable `NODE_PRIORITIZED_PATH` which has a quicker module loading, please see #274 for the details.
And we added a heap profiler tooling as well, which could help developers to see how is your programs looks like in vm. [docs/devs/Optimization-Tips.md#heap-profiler](https://github.com/Rokid/ShadowNode/blob/master/docs/devs/Optimization-Tips.md#heap-profiler) is a …

working on 0.10.x

---

src/js/iotjs.js
test/run_fail/test_iotjs_type_error.js
test/testsets.json

test/run_fail/test_iotjs_type_error.js

 debugger: Error.stack deal with top level source

---

src/js/events.js

events: change intial way (#335)

---

docs/api/Events.md
src/js/events.js
test/run_pass/test_events_new_listener.js

events: emit `newListener` on new listener

---

docs/api/Process.md
src/js/iotjs.js
src/js/promise.js
test/run_fail/test_promise_unhandled_rejection.js
test/run_pass/test_process_unhandled_rejection.js
test/testsets.json

promise: emit unhandledRejection on process

---

src/modules/iotjs_module_timer.c

timer: update looper time before creating timer

---

deps/libtuv/src/unix/core.c
docs/api/Process.md
src/js/child_process.js
src/js/constants.js
src/js/iotjs.js
src/modules.json
src/modules/iotjs_module_signal.c
src/modules/iotjs_module_signal.h
test/run_pass/test_signal_simple.js
test/testsets.json

Added the signal events support by Node.js API, and this is mainly the precondition of simplifying the progress of taking the snapshot, and other debugger/dump usages.
/cc @lolBig @legendecas @fighterkin @algebrait

process: add signal events support

---

deps/jerry/tests/jerry/regression-test-issue-2105.js

jerry: pass regression-test-issue-2105 for heapdump

---

src/napi/node_api_async.c

async-work: fix complete callback segv/ticks

---

src/iotjs_env.c
src/iotjs_env.h
src/modules/iotjs_module_process.c
tools/testrunner.py

process: set immediate shall start an idle handle to activate uv_loop

---

deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-date.c
deps/jerry/tests/jerry/regression-test-issue-2272.js

Original:
https://github.com/jerryscript-project/jerryscript/pull/2274

jerry: Date.now shall return an integer

---

test/run_pass/test_net_https_destroy.js
tools/travis_script.py

test: fix wrong travis diff target introduced by #425

---

CMakeLists.txt
package.json

Now let's working on v0.11.x, and in the past 2 months, we have the following features summary.
- n-api: support thread-safe function, `new.target` and `TypedArray`.
- n-api: upgrade the header and test suite to LTS(10.13.0).
- child_process: introduce binary protocol to optimize the ipc performance by _5~6x_.
- promise: optimize the performance by _70%_ via freeze objects.
- jerry: implement the source info, that optimizes the backtrace prints.
- process: add signal events.
- process: add shebang parser.
- jerry: support the keywords `class` and `extends`.
- os: support `{get,set}Priority` methods.
- n-api: asserts on execution thread
- n-api: napi_make_callback triggers next tick
- n-api: fix complete callback segv/ticks on async-work
- n-api: code is optional on create error
- n-api: …

Working on v0.11.x

---

deps/libtuv/include/uv.h
deps/libtuv/src/unix/darwin.c
deps/libtuv/src/unix/freebsd.c
deps/libtuv/src/unix/linux-core.c
deps/libtuv/src/unix/netbsd.c
deps/libtuv/src/unix/openbsd.c
deps/libtuv/src/unix/sunos.c
docs/api/OS.md
src/js/os.js
src/modules/iotjs_module_os.c
test/run_pass/test_os.js
test/testsets.json

os: build bcast address interface.

---

README.md

readme: polishing readme statements

---

test/deps/yarn.lock

Connection to taobao registry was not up to expectation nor stable on travis CI.

chore: use yarnpkg registry to speed up CI

---

deps/jerry/jerry-core/ecma/operations/ecma-function-object.c
deps/jerry/tools/gen-magic-strings.py

jerry: fix failure of gen-magic-string.py for leading spaces

---

.travis.yml
cmake/iotjs.cmake
tools/build.py

build: option to build a statically linked executable

---

.eslintignore
tools/common_js/logger.js
tools/common_js/module/console.js
tools/common_js/option_parser.js
tools/common_js/util.js
tools/iotjs_build_info.js
tools/report-esfeature.js

lint: enable lint on `tools`

---

tools/travis_script.py

build: always run jerry tests on non-PR branch

---

src/modules/iotjs_module_process.c
test/run_pass/test_module_require.js

module: avoid error when require an empty module fix/gh-330.

---

deps/jerry/jerry-core/parser/js/js-parser-expr.c
deps/jerry/tests/jerry/es2015/regression-test-issue-502.js

jerry: correct class constructor literal index

---

deps/jerry/docs/02.API-REFERENCE.md
deps/jerry/jerry-core/api/jerry.c
deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-string.c
deps/jerry/jerry-core/include/jerryscript-core.h
deps/jerry/jerry-core/vm/vm.c
deps/jerry/jerry-ext/handler/handler-print.c
deps/jerry/tests/jerry/es2015/symbol-computed-object-literal.js
deps/jerry/tests/jerry/es2015/symbol-prototype-tostring.js
deps/jerry/tests/unit-core/test-api-value-type.c
deps/jerry/tests/unit-core/test-symbol.c
docs/api/N-API.md
src/napi/node_api_property.c
src/napi/node_api_value.c
test/napi-testsets.json

n-api: add napi_create_symbol support

---

cmake/iotjs.cmake

build: support cmake 2.8 string concat

---

.travis.yml

build: fix the travis deploy reponame

---

cmake/iotjs.cmake
src/iotjs_util.c
src/napi/node_api_env.c

Also enables packaging headers/libraries on release

build: install headers on static build

---

docs/api/Process.md
src/js/iotjs.js
src/modules/iotjs_module_process.c
test/run_pass/test_process_kill.js
test/run_pass/test_signal_simple.js
test/testsets.json

process: fix process kill to send signal to target process

---

docs/contributing/Releases.md

Documents on releases process.

doc: Releases

---

src/js/mqtt.js
test/run_pass/test_mqtt_timeout.js
test/testsets.json

MQTT: fix connect timeout not working

---

src/napi/node_api_function.c
test/napi-testsets.json
test/napi/napi_arguments.c
test/napi/napi_arguments_rectify_argc.test.js

n-api: napi_get_cb_info with NULL argv but non-zero argc

---

tools/js2c.py

build: fix compile error on python3

---

.gitignore
docs/api/MQTT.md
src/js/mqtt.js
test/run_pass/test_mqtt_client.js
test/run_pass/test_mqtt_disconnect.js
test/run_pass/test_mqtt_end.js
test/run_pass/test_mqtt_error.js
test/run_pass/test_mqtt_event_1.js
test/run_pass/test_mqtt_event_2.js
test/run_pass/test_mqtt_event_3.js
test/run_pass/test_mqtt_reconnect_1.js
test/run_pass/test_mqtt_reconnect_2.js
test/run_pass/test_mqtt_reconnect_3.js
test/run_pass/test_mqtt_timeout.js

MQTT: fix event flow & add more tests

---

src/js/constants.js
src/modules/iotjs_module_constants.c
test/run_pass/test_constants.js
test/run_pass/test_signal_simple.js
test/testsets.json

It fixes https://github.com/yodaos-project/ShadowNode/issues/560 by fixing the missing signal `SIGCHLD`.

constants: refactors the module to use os defines
