yodaos-project/ShadowNode

cmake/iotjs.cmake

Add `CMAKE_DL_LIBS` to `target_link_libraries()` to find the libdl.

build: fix the libdl linking issue

---

docs/api/IoT.js-API-Crypto.md
src/js/crypto.js
src/modules.json
src/modules/iotjs_module_crypto.c
src/modules/iotjs_module_crypto_hash.c

Adds the following functions:
- `crypto.getHashes()`
- `crypto.createHash()`
and the `Hash` class which provides:
- `.update(buffer, inputEncoding)`
- `.digest(encoding)`
This also tries to complete the list on #2.

 crypto: add Hash functions

---

src/js/stream_readable.js

The `pipe` should returns the dest for the following usage:
```js
a.pipe(b).pipe(c);
```

stream: add pipe to dest and returns dest

---

deps/jerry/jerry-core/parser/js/js-lexer.c

We should support the oct literal in standard way: https://www.ecma-international.org/ecma-262/8.0/index.html#prod-OctalIntegerLiteral, which is:
```
0o666
0O666
```

jerry: support the ecma standard oct literal

---

src/js/buffer.js

The first argument of `Buffer.prototype.toString()` should be hex string.

buffer: fix toString and constructor to consistent with node

---

src/js/console.js
src/js/iotjs.js

Changes:
- add `Error.captureStackTrace()` polyfills
- add `stdout/stderr` on the `process` object, which only owns the following props:
- property: `isTTY`, always `false`.
- method: `write(text)`.

Error: add captureStackTrace polyfills, and add stdout/stderr

---

src/js/string_decoder.js
src/modules.json

This module is used by the third-party `iconv-lite`, we have to support that :)

string_decoder: expose module

---

build.config

Increasing the heap memory to 16x might be more proper for Node.js-compatible runtime :)

config: increase the default heap memory to 4096

---

CMakeLists.txt

This adds -fPIC to fix the shared library linking problem on Linux :)

build: add -fPIC for fixing relocation in shared library

---

src/js/iotjs.js
src/js/module.js

This prints the `SyntaxError`'s source file as:
```shell
uncaughtException: SyntaxError: Primary expression expected. [line: 4, column: 2] at
/Users/yorkieliu/workspace/shadownode-debug-playground/bar.js
```

module: prints the latest loaded module id when syntax error

---

src/modules/iotjs_module_mqtt.c

Use chunk size as the buffer size in `ReadPacket()`.

mqtt: fix the read connect length

---

src/js/mqtt.js
src/js/tls.js
src/modules/iotjs_module_constants.c
src/modules/iotjs_module_mqtt.c
src/modules/iotjs_module_tls.c

- limit buffer size with 16k(defined by MBEDTLS_SSL_MAX_CONTENT_LEN) for iotjs_tlswrap_encode_data
- tls encode incoming data multi times when data is larger than 16k
- alloc 1m heap memroy for MqttGetPublish buffer instead of dynamic stack memory

tls: bug fix

---

src/js/tls.js

Good catch from @lolBig, just call `.end()` in this case.
/cc @Rokid/node-js

tls: end the connection when receive close_notify from peer via TLS

---

src/js/buffer.js
test/run_pass/test_buffer.js

Adds the following methods:
- `readInt16LE`
- `readInt32LE`
- `readFloatLE` not working in this PR for now

buffer: add readInt16LE/readInt32LE/readFloatLE

---

src/js/buffer.js
test/run_pass/test_buffer.js

This fixes `new Buffer([0xb5, 0x01])` return the negative number :)

buffer: fix readInt methods, should use builtin uint

---

cmake/iotjs.cmake

Should not re-install the library when not in library only. This fixes the installing issue on /usr/lib and /lib.

build: fix the staging and target installing path

---

deps/jerry/jerry-core/api/jerry.c
deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c
deps/jerry/jerry-core/include/jerryscript-core.h
deps/jerry/jerry-core/jcontext/jcontext.c
deps/jerry/jerry-core/jcontext/jcontext.h
src/iotjs_binding_helper.c
src/js/iotjs.js
src/js/util.js
src/modules/iotjs_module_process.c
test/node/parallel/test-http-catch-uncaughtexception.js
test/run_pass/test_iotjs_error_stack.js
test/run_pass/test_util.js
test/testsets.json

Expected behavior:
```js
function namedFunction () {
return new Error('foobar')
}
console.log(namedFunction())
// Error: foobar
//     at namedFunction (/some/where/the/script/locates.js:1:10)
function capturePlainObject () {
var e = {}
Error.captureStackTrace(e)
return e
}
console.log(capturePlainObject().stack)
//     at capturePlainObject (/some/where/the/script/locates.js:10:10)
```
close #118

stacktrace: attach stack trace to error instance

---

src/modules/iotjs_module_process.c

Just prints the `dlerror` result correctly :)
/cc @Rokid/nodejs

process: print the dlopen error correctly

---

.eslintignore
benchmark/README.md
benchmark/_cli.js
benchmark/buffer/buffer-base64-decode.js
benchmark/buffer/buffer-base64-encode.js
benchmark/buffer/buffer-hex.js
benchmark/buffer/buffer-tostring.js
benchmark/buffer/buffer-zero.js
benchmark/common.js
benchmark/run.js
src/js/module.js

Initialized the benchmark(copy from nodejs), and the results on my mac is:
```
buffer/buffer-base64-decode.js
32768 32
buffer/buffer-base64-decode.js n=32 size=32768: 2,353.614552516459
buffer/buffer-base64-encode.js
buffer/buffer-base64-encode.js n=32 len=16384: 1,780.9553979756324
buffer/buffer-hex.js
buffer/buffer-hex.js n=4096 len=64: 23,693.716692424714
buffer/buffer-tostring.js
buffer/buffer-tostring.js n=1024 len=0 args=0 encoding="": 196,401.02788319203
buffer/buffer-zero.js
buffer/buffer-zero.js type="buffer" n=16: 27.505013850295846
```
And the Node.js runs the same source code:
```
buffer/buffer-base64-decode.js
32768 32
buffer/buffer-base64-decode.js n=32 size=32768: 7,263.34764969419
buffer/buffer-base64-encode.js
buffer/buffer-base64-encode.js n=32 len=16384: …
```

benchmark: add perf for buffer modules

---

src/js/net.js

If not specified, we use IPv4 as the default option, this is compatible with some routers which did not support IPv6.

net: use ipv4 for dns family by default

---

src/iotjs.c

This fixes the `Math.random()` outputs the same order result in different process.
```js
for (var i = 0; i < 10; i++)
console.log(Math.random());
```
Always output:
```
*.000007826369255781174
*.1315377880819142
*.755605321843177
*.4586501317098737
*.5327672371640801
*.21895918622612956
*.04704461619257927
*.6788647165521979
*.6792964055202902
*.9346928955055773
```

iotjs: call srand to set random seed

---

benchmark/console/common.js
src/js/console.js

BTW, added the benchmark for `console.log`.
```sh
> console/common.js n=128: 22,295.029427697045   #before
> console/common.js n=128: 38,630.9784834504     #after
```
The performance under this case is optimized 57% up :)

console: optimize the log function for single param

---

src/js/http_outgoing.js
test/run_pass/test_net_http_request_response.js

This fixes #102, now we have http/https is to set `Content-Length` by default if body is present. 
/cc @legendecas @lolBig

http: set content-length if not set and body is set

---

deps/jerry/jerry-core/api/jerry.c
src/js/iotjs.js

We should use `error.stack` as the outputs when not catching `uncaughtException`, and add the message line in front of `.stack`.

stack: should print error.stack when not catching uncaughtException

---

src/js/net.js
test/run_pass/test_net_end.js
test/testsets.json

Pipe doesn't own `shutdown` function, which causes crash when the writable is finished.
Fixes #150

net: check if shutdown is a function.

---

src/iotjs_handlewrap.c

In `Release` build doesn't has the `flag_create` option, we should find another way to validate if it is handwrap.

iotjs: fix the compile failure when release build

---

src/js/http_outgoing.js
test/run_pass/test_net_headers.js

Allow the following:
```js
res.setHeader('content-length', 0);
```

http: allow zero value for content-length by correct check for value

---

docs/api/Buffer.md
src/js/buffer.js
test/run_pass/test_buffer.js

Implements the function `buffer.writeInt32LE()` which [Rokid/node-turen](https://github.com/Rokid/node-turen) depends on it.
/cc @legendecas @LanFly

buffer: add writeInt32LE impl and docs

---

src/iotjs.c
src/iotjs_env.c
src/iotjs_env.h
src/iotjs_handlewrap.c
src/iotjs_handlewrap.h
src/iotjs_list.c
src/iotjs_list.h
src/iotjs_string.h
src/iotjs_util.h

Fixed the build failure at #157 and a real fix to #143, it caused by the following error still:
```sh
/Users/travis/build/Rokid/ShadowNode/src/iotjs_handlewrap.c:136:20: error: comparison of address of 'handlewrap->unsafe' equal to a null pointer is always false [-Werror,-Wtautological-pointer-compare]
if (&handlewrap->unsafe == NULL) {
~~~~~~~~~~~~^~~~~~    ~~~~
1 error generated.
```
This patch is related with how ShadowNode/IoT.js releases all the `HandleWrap` when program exits. The `HandleWrap` owns the `uv_handle_t` field. IoT.js releases them by `uv_walk` and its callback, which is called with an `uv_handle_t` object. 
The IoT.js asserts that every `uv_handle_t`'s `data` field is type of `HandleWrap`, That's working for these original modules, but now crashed for our new D-Bus …

 iotjs, env: add handlewrap_queue for clean it more clear

---

deps/jerry/tests/unit-core/test-snapshot.c

Fix the following warnings:
```
/Users/travis/build/Rokid/ShadowNode/deps/jerry/tests/unit-core/test-snapshot.c:226:49: warning: format specifies type 'int' but the argument has type 'unsigned long' [-Wformat]
fprintf(stdout, "snapshot size: %d / %d\n", sizeof (expected_data), global_mode_snapshot_size);
~~          ^~~~~~~~~~~~~~~~~~~~~~
%lu
/Users/travis/build/Rokid/ShadowNode/deps/jerry/tests/unit-core/test-snapshot.c:226:73: warning: format specifies type 'int' but the argument has type 'size_t' (aka 'unsigned long') [-Wformat]
fprintf(stdout, "snapshot size: %d / %d\n", sizeof (expected_data), global_mode_snapshot_size);
~~                             ^~~~~~~~~~~~~~~~~~~~~~~~~
%zu
2 warnings generated.
```

jerry: fix test warnings

---

docs/api/Stream.md
src/js/buffer.js
src/js/net.js
src/js/stream_writable.js
test/run_pass/test_stream_duplex.js

writable#write shall pass chunk encoding to underlying stream implementation
3 api have changed in this PR. However the arguments order in 2 of them are not necessarily forced in order of `chunk, encoding, callback`, as second argument encoding is optional. 
A break change is introduced in this PR to `Writable#_write`. The function signature has changed from
```typescript
Writable#_write(chunk: Buffer | string, callback: Function, onwrite: Function)
```
to 
```typescript
Writable#_write(chunk: Buffer | string, encoding: string, callback: Function, onwrite: Function)
```

stream: writable#write shall respect chunk encoding

---

docs/api/HTTP.md
src/js/http_client.js
src/js/http_outgoing.js
test/run_pass/test_http_transfer_encoding.js
test/run_pass/test_net_http_request_response.js
test/testsets.json

Expect resolving #133 
http client:
http server:
------

http: chunked transfer encoding

---

src/modules/iotjs_module_mqtt.c

This found by this [codacy page](https://app.codacy.com/app/yorkie/ShadowNode/issues?bid=7916123&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJDIl19LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOlsyMTE5XX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W251bGxdfSx7InZhbHVlcyI6W119XQ==) as the following:
- Struct member is never used.
- Statements following return, break, continue, goto or throw will never be executed.
Request reviews from @legendecas @algebrait :)

mqtt: remove unused members and spaces

---

src/iotjs.c
src/iotjs_debuglog.c
src/iotjs_debuglog.h
src/iotjs_env.c
test.js

Now we are closer to Node.js style command line tool:
```sh
> iotjs -v
v0.8.5
> iotjs --version
v0.8.5
> iotjs --help
Usage: iotjs [options] [script | script.js] [arguments]
Options:
-v, --version              print version
-h, --help                 print help
--loadstat                 print the load statistics
--memstat                  print the memory statistics
--show-opcodes             print the opcodes of running script
--start-debug-server       activate the debugger server
Environment variables:
NODE_DISABLE_COLORS          set to 1 to disable colors in the REPL
NODE_PATH                    ':'-separated list of directories
prefixed to the module search path
Documentation can be found at https://github.com/Rokid/ShadowNode/tree/master/docs
```

iotjs: improve the cli options, more like nodejs

---

.travis.yml
src/modules/iotjs_module_child_process.c
test/memory/child_process.js

This is going to fix almost #195, the memory leaks from `child_process`. This shows the data list of the leaks:
| codebase | rss(from) | rss(to) | leaked bytes |
|-----------|----------|--------|--------------|
|  [master](https://github.com/Rokid/ShadowNode/tree/master)     | 2654208 | 3555328 | 901120 |
| [fix/gh-195](https://github.com/Rokid/ShadowNode/tree/fix/gh-195) | 2576384 | 3002368 | 425984 |
Added a memory test script as well, someone could run by:
```sh
$ iotjs test/memory/child_process.js
Memory Leak Summary(389 samples):
Rss(From): 2654208
Rss(End ): 3555328
Detects 901120 bytes
```
@legendecas @lolBig Needs your reviews on this PR.

child_process: free blocks from strdup() which causes memory leaks

---

src/modules/iotjs_module_pipe.c
test/memory/issue/issue-199/child.js
test/memory/issue/issue-199/parent.js

This fixes #199 which caused by not calling `iotjs_string_destroy()` when buffer write is done.
/cc @lolBig @legendecas

pipe: release iotjs_string when write complete

---

src/modules/iotjs_module_child_process.c
tools/travis_script.py

After fix this, valgrind on ubuntu pass all. So --no-check-valgrind can be removed.

iotjs: fix memory leak

---

src/iotjs_binding.c
test/run_pass/test_console.js

Upstream commit: https://github.com/Samsung/iotjs/commit/68e84c78c9cee2979831c842e57976ed9ca73ea8.
The detailed case is here: https://github.com/Samsung/iotjs/issues/1562.
/cc @lolBig

iotjs: change iotjs_jval_as_string to use utf8 buffers

---

CMakeLists.txt
package.json

Hello @Rokid/nodejs, Let's working on ShadowNode v0.9 now!
In _v0.8.x_, we have 53 commits pushed, 36 Pull Request merged and 30 issues closed. Let's see what changes we have done.
- Add `Function.prototype.name` with _FEATURE_FUNCTION_NAME_ #123.
- Add native function `jerry_has_property_by_index()` #139.
- Add CPU Profiler with _FEATURE_CPU_PROFILER_ which supports to generate flamegraph #176.
- Promise: remove native and use the pure javascript implementation #215.
- Record magic string id for builtin objects and routines #160.
- Use tmpfile() for parser dump storage instead a normal file #178.
- Fix uninitialized memory malloced #165.
- Fix test and build warnings #170 #206.
- Update upstream travis script #157.
- Remove jsdriver and use new Python-based test driver from upstream …

Release Proposal: working on v0.9.x

---

deps/jerry/jerry-ext/handle-scope/handle-scope-allocator.c
deps/jerry/jerry-ext/handle-scope/handle-scope-internal.h
deps/jerry/jerry-ext/handle-scope/handle-scope.c
deps/jerry/jerry-ext/include/jerryscript-ext/handle-scope.h
deps/jerry/tests/unit-ext/test-ext-handle-scope-root.c

Series convenience methods of root handle scope.
Closes root handle scope on iotjs exit.

jerryx: root handle scope convenience methods

---

src/iotjs.c
test/run_pass/test_process_exit.js
test/run_pass/test_process_exit_handler.js

This fixes the case when we process.exit in the exit handler. To reproduce this case, just run the following code:
```js
process.on('exit', function() {
process.exit(0)
});
```
Which [shadow-node/tape](https://github.com/shadow-node/tape) is using it, and it gives an assertion error:
```
$ /Users/yorkieliu/workspace/shadow-node/src/iotjs_env.c:286: Assertion '_this->state < kExiting' failed.
```
This is because:
- Emit `exit` handler
- Call `process.exit()` in handler, this makes `state` to be `kExiting`.
- Call `iotjs_environment_go_state_exiting()`
- Failed on assertion because the state is not less than `kExiting`.
To fix this problem, just check the global state is `kExiting` before `go_state_exiting()` always.

env: check exiting state before set after emit exit event

---

src/modules/iotjs_module_console.c

The original implementation would make a huge number of `syscalls` to `write()`.
/cc @legendecas

console: improve the performance on printf

---

deps/jerry/jerry-ext/handle-scope/handle-scope-internal.h
deps/jerry/jerry-ext/handle-scope/handle-scope.c
deps/jerry/jerry-ext/include/jerryscript-ext/handle-scope.h
deps/jerry/tests/unit-ext/test-ext-handle-scope-evade.c
deps/jerry/tests/unit-ext/test-ext-handle-scope-remove.c
src/napi/node_api_module.c

There may be some handles we have to hand over it's life time management to jerry engine, and totally give up it's reference. Rather escaping it and keep a ref to the value in parent scope, the reference shall be deleted from the scope.

handle-scope: complete escaping of handles

---

src/modules/iotjs_module_dbus.c

fix crash caused by release jdbus while require dbus module

DBus: fix require crash

---

src/internal/node_api_internal.h
src/napi/node_api_value.c

- napi_create_array
- napi_create_array_with_length
- napi_create_object
- napi_get_array_length
- napi_get_prototype
- napi_get_value_bool
- napi_get_boolean
- napi_get_global
- napi_get_null
- napi_get_undefined
- napi_coerce_to_bool
- napi_coerce_to_number
- napi_coerce_to_object
- napi_coerce_to_string
- napi_typeof
- napi_is_array
- napi_is_arraybuffer
- napi_is_error
- napi_is_typedarray

napi: working with javascript values

---

docs/api/Module.md
src/js/module.js
test/node/parallel/test-assert.js
test/node/parallel/test-http-catch-uncaughtexception.js
test/node/parallel/test-http-status-message.js
test/node/parallel/test-http-write-head.js
test/node/parallel/test-net-after-close.js
test/node/parallel/test-net-bind-twice.js
test/node/parallel/test-net-end-without-connect.js
test/node/parallel/test-net-keepalive.js
test/node/parallel/test-timers-clear-null-does-not-throw-error.js
test/run_pass/require1/test_index/index.js
test/run_pass/require1/test_index2/index_test.js
test/run_pass/require1/test_pkg/main.js
test/run_pass/require2/node_modules/foobar/test.js
test/run_pass/test_module_cache.js
test/run_pass/test_module_json.js
test/run_pass/test_module_require2.js
test/testsets.json

Give the following optimizations:
- search rules:
- If the `id` is a relative path, directly search by `__dirname`, no global module and `node_modules`.
- If the `id` is a global path, directly try with file.
- tweak the order of global paths, level up the `NODE_PATH`.
- remove the retry with `index` after package main property is absence, because checked already before.
Also, this patch removes the way to load relative module without dots:
```js
require('test/foobar') // doesn't work
require('./test/foobar') // it's working
```

module: optimize the path searching

---

src/js/debug.js
src/js/module.js
src/modules.json

This is for logging informations for internal modules, for example:
```bash
$ NODE_DEBUG=module iotjs test.js
```

debug: add a new internal debug module for debugging based on env

---

.clang-format
config/nuttx/stm32f4dis/app/iotjs_main.c
config/nuttx/stm32f4dis/app/jerry_port.c
src/internal/node_api_internal.h
src/internal/node_api_internal_types.h
src/iotjs_list.c
src/iotjs_list.h
src/modules/iotjs_module_crypto.c
src/modules/iotjs_module_tls_bio.c
src/modules/iotjs_module_tls_bio.h
src/napi/node_api_env.c
src/napi/node_api_function.c
src/napi/node_api_lifetime.c
src/napi/node_api_module.c
src/platform/tizenrt/iotjs_main_tizenrt.c

See https://clang.llvm.org/docs/ClangFormatStyleOptions.html
**DerivePointerAlignment (bool)**
> If true, analyze the formatted file for the most common alignment of & and *. Pointer and reference
> alignment styles are going to be updated according to the preferences found in the file. 
> PointerAlignment is then used only as fallback.
**PointerAlignment (PointerAlignmentStyle)**
> Pointer and reference alignment style.
Just set the `DerivePointerAlignment` to false to fix our styles.

build: set DerivePointerAlignment to false

---

src/internal/node_api_internal.h
src/modules/iotjs_module_process.c
src/napi/node_api.c
src/napi/node_api_env.c
src/napi/node_api_function.c
src/napi/node_api_lifetime.c
src/napi/node_api_module.c
src/napi/node_api_object_wrap.c
src/napi/node_api_property.c
src/napi/node_api_value.c
test/addons-napi/8_passing_wrapped/test.js
test/addons-napi/test_async/test-async-hooks.js
test/addons-napi/test_async/test-loop.js
test/addons-napi/test_buffer/test.js
test/addons-napi/test_callback_scope/test-async-hooks.js
test/addons-napi/test_constructor/test.js
test/addons-napi/test_constructor/test2.js
test/addons-napi/test_error/test.js
test/addons-napi/test_exception/test.js
test/addons-napi/test_function/test.js
test/addons-napi/test_general/test.js
test/addons-napi/test_general/testInstanceOf.js
test/addons-napi/test_make_callback_recurse/test.js
test/addons-napi/test_new_target/test.js
test/addons-napi/test_threadsafe_function/test.js
test/addons-napi/test_typedarray/test.js
test/napi-testsets.json
tools/pull-napi.sh
tools/testrunner.py

Issues fixed in this PR:
1. In most N-API functions, there is an in-out pointer parameter to retrieve return values, yet this pointer could be NULL anyway - it has to be ensured no value were unexpectedly written to NULL pointer.
2.  If any non-napi-ok status code is returned in N-API functions, there should be an error code and error message temporarily stored in napi-env and can be fetched by `napi_get_last_error_info` until next napi function called.

napi: null in-out return pointer

---

src/napi/node_api_function.c
src/napi/node_api_value.c
test/napi-testsets.json
test/napi/binding.gyp
test/napi/common.h
test/napi/napi.test.c
test/napi/napi_string.c
test/napi/napi_string.test.js

Issues fixed in this PR:
- no null terminator added on end of string on copying string value
- returning number value `0` on N-API function would be transformed to `undefined`: now no tranformation is performed

napi: null terminator on copying string value

---

src/js/console.js
src/js/util.js

Format console.log's param using util.formatValue when the function has only one param. The performance is the same as before:
```
console/common.js n=128: 6,353.840618673461   #before
console/common.js n=128: 6,344.13890531784     #after
```

console: fix print object for single parameter

---

src/js/dbus.js

Exposes the low-level member `_bus` for signal handler usage.

dbus: expose the internal member privately

---

src/js/crypto.js
src/modules/iotjs_module_crypto_hash.c
test/run_pass/test_crypto_hash.js

fixed an issue that result of calculating hash from raw buffer is not correct

fix: cipher.update shall use underlying buffer directly

---

benchmark/url/append-url.js
benchmark/url/url-format.js
benchmark/url/url.json

Benchmark results of appending url manually between formatting with `url.format`:
```
$ node benchmark/run url
url/append-url.js
url/append-url.js n=128: 136,929.44282553907
url/url-format.js
url/url-format.js n=128: 51,543.58956806069
```
```
$ iotjs benchmark/run url
url/append-url.js
url/append-url.js n=128: 10,643.118766396015
url/url-format.js
url/url-format.js n=128: 2,309.9444480015986
```

benchmark: url.format

---

test/testsets.json

We didn't include the case on `testsets.json` at #352, this is to fix the issue.

test: add test_net_https_destroy.js to testset

---

src/modules/iotjs_module_dbus.c
test/run_pass/test_dbus_service_and_call.js

This supports the `double` type for dbus module.

dbus: support returning double type

---

src/js/http_client.js
src/js/https_client.js
src/modules/iotjs_module_os.c
test/node/parallel/test-http-abort.js

1. when the network is disconnected,  the socket cloud not been destroyed if the HTTP/HTTPS request through ip
2. invoke uv_free_interface_addresses to free uv_interface_address_t*
3. remove the 'lookup' event listener in https

leak: fix http/https and os leak

---

docs/api/N-API.md

Following methods are supported in latest ShadowNode
- napi_make_callback
- napi_open_callback_scope
- napi_close_callback_scope

doc: update supported n-api methods list

---

src/js/mqtt.js
test/run_pass/test_mqtt_client.js
test/run_pass/test_mqtt_sub_pub.js
test/testsets.json

The timer for *Keep Alive* should be cleared if we explicitly disconnect it.
/cc @lolBig @legendecas

mqtt: clean up the keepalive timer when disconnecting

---

deps/jerry/jerry-core/api/jerry.c
deps/jerry/jerry-core/ecma/operations/ecma-function-object.c
deps/jerry/tests/unit-core/test-api.c

External functions are treated as incomplete creation, which prototype is set to be undefined, which causes the `has_instance` doesn't work at external function.
This fixes #294 and #295.

jerry: set prototype/constructor for external functions

---

benchmark/promise/resolve-empty-array.js
benchmark/promise/resolve-statically.js
benchmark/promise/then.js
src/js/promise.js

The optimized `Promise` comparison:
| versions | 1 | 2 | 3 | 4 | 5 | Avg |
|----------|--|--|--|--|--|--|
| `before#then` | 2,500 | 2,189 | 2,560 | 2,716 | 2,191 | 2,431 |
| `after#then` | 3,056 | 3,149 | 3,383 | 3,270 | 3,694 | 3,310 |
| `before#resolve` | 1,717 | 1,589 | 1,744 | 1,684 | 1,770 | 1,700 |
| `after#resolve` | 2,848 | 2,764 | 3,433 | 2,622 | 3,023 | 2,938 |
The performance slots are:
- `then`, removes to create duplicated empty function, and creates at start.
- `Promise.resolve`:
- skips `doResolve`, and immediately calls `resolve(self, value)` instead.
- introduces freeze promise objects, currently for `undefined`, `true` and `false`.

promise: optimize the performance on .then and static resolve

---

deps/jerry/jerry-core/debugger/debugger.h
deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.c
deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.h
deps/jerry/jerry-core/ecma/operations/ecma-function-object.c
deps/jerry/tests/jerry/es2015/regression-test-issue-2414.js

This merges the upstream PR(https://github.com/jerryscript-project/jerryscript/pull/2414) which optimizes the following:
> Furthermore add a construct flag, which disallows calling certain functions without new. Constructing bound arrow functions correctly throws error now.
BTW, https://github.com/jerryscript-project/jerryscript/commit/65ae949dc32ebf8c06df8f5e0fd4441b1bef5009 is valuable to merge into our own fork, either.

jerry: merge a59cf4f from upstream to optimize the function call

---

cmake/iotjs.cmake

Within some parallel builds, it occasionally gets a build error on libmqtt_packet depenedency.

build: add dependencies for iotjs.cmake which depends on others

---

src/js/events.js

fixes an edge issue:
```js
var obj = {}
EventEmitter.prototype.on.apply(obj, ['foobar'])
```
as this is not an officially documented usage, test case is not included by intent.

events: cannot read property 'newListener' of undefined

---

src/js/mqtt.js
test/run_pass/test_mqtt_client.js

- change the trigger timing of the connect event
- add close event when the connection is disconnected, see [mqtt.js](https://github.com/mqttjs/MQTT.js#event-close)

MQTT: update event trigger timing

---

src/napi/node_api_value.c
test/napi/napi_error.c
test/napi/napi_error_throw.test.js

According to N-API docs, second argument of napi_create_error/napi_create_type_error/napi_create_range_error shall be an optional string typed JS value.

n-api: code is optional on create error

---

docs/api/N-API.md
src/internal/node_api_internal_types.h
src/napi/node_api_function.c
test/napi-testsets.json
test/napi/binding.gyp
test/napi/napi_new_target.c
test/napi/napi_new_target.test.js

Issues encountered in this PR:

n-api: new.target

---

deps/libtuv/src/unix/linux-core.c

Merges https://github.com/bnoordhuis/libuv/commit/f43c66 into tuv, that:
> Removes the support for kernels that don't support epoll_pwait()
> now that the minimum requirements are kernel 2.6.32 + glibc 2.12.

uv: drop code path for epoll_pwait-less kernels

---

src/iotjs_util.c
src/iotjs_util.h
src/napi/node_api_env.c

Currently stack trace only prints on linux platform. While macOS actually support backtrace too, this PR enables backtrace on macOS platform.

util: IOTJS_ASSERT prints stack trace on macOS

---

docs/api/N-API.md
src/internal/node_api_internal.h
src/internal/node_api_internal_types.h
src/napi/node_api_tsfn.c
test/napi-testsets.json
test/napi/binding.gyp
test/napi/napi_tsfn.c
test/napi/napi_tsfn.test.js

Unit tests depends on #406.
Introduce thread safe functions into N-API. Simplify complex native add-ons to notify JavaScripts in a work thread without blocking work thread nor main thread.

n-api: thread safe functions

---

docs/api/N-API.md
include/node_api.h
include/node_api_types.h
test/addons-napi/7_factory_wrap/binding.cc
test/addons-napi/7_factory_wrap/myobject.cc
test/addons-napi/7_factory_wrap/myobject.h
test/addons-napi/7_factory_wrap/test.js
test/addons-napi/8_passing_wrapped/test.js
test/addons-napi/README.md
test/addons-napi/test_async/test-loop.js
test/addons-napi/test_general/testFinalizer.js
test/addons-napi/test_general/test_general.c

n-api: update n-api headers/test sets to LTS version 10.13.0

---

deps/jerry/jerry-core/api/jerry.c
deps/jerry/jerry-core/ecma/base/ecma-globals.h
deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-json.c
deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-object.c
deps/jerry/jerry-core/ecma/operations/ecma-objects.c
deps/jerry/jerry-core/ecma/operations/ecma-objects.h
deps/jerry/jerry-core/vm/opcodes.c

Picked from upstream https://github.com/jerryscript-project/jerryscript/pull/2598
A pre-requirement to Symbol implementation. Which simplifies future support of [Object.getOwnPropertySymbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols).

jerry: reduce the argument count of ecma_op_object_get_property_names

---

docs/api/N-API.md
src/internal/node_api_internal_types.h
src/napi/node_api_value.c
test/napi-testsets.json
test/napi/binding.gyp
test/napi/napi_typedarray.c
test/napi/napi_typedarray.test.js

n-api: ArrayBuffer/TypedArray support

---

src/js/internal/process/next_tick.js

close #432 
Before
```
process/next_tick_create.js
process/next_tick_create.js n=1024: 26,698.986345867223
process/next_tick_create_5.js
process/next_tick_create_5.js n=1024: 27,663.1749112293
process/next_tick_parallel.js
process/next_tick_parallel.js n=1024: 18,206.212308117814
process/next_tick_parallel_5.js
process/next_tick_parallel_5.js n=1024: 12,624.287590739534
process/next_tick_recursive.js
process/next_tick_recursive.js n=1024: 52,327.725272901356
process/next_tick_recursive_5.js
process/next_tick_recursive_5.js n=1024: 20,872.33860102376
```
After
```
process/next_tick_create.js
process/next_tick_create.js n=1024: 25,598.715584445552
process/next_tick_create_5.js
process/next_tick_create_5.js n=1024: 22,949.062561049494
process/next_tick_parallel.js …
```

process: memory leaks on recursive ticking

---

src/napi/node_api_value.c
test/napi/napi_typedarray.c

n-api: data pointer was NULL on getting typed array info

---

src/js/mqtt.js
test/run_pass/test_mqtt_client.js

The MQTT protocol uses this option in seconds, the current 60*1000
causes the mqtt keep alive is too long from server-side.

mqtt: change the option `keepalive` in seconds.

---

cmake/iotjs.cmake

executable `iotjs` is not installed on building dynamically linked libiotjs.

build: install executables while libiotjs dynamically linked

---

src/js/promise.js
test/run_pass/test_iotjs_promise_then_bind.js

The `newValue.then` should bind itself.
Benchmark:
  | 1 | 2 | 3 | 4 | 5 | AVG
-- | -- | -- | -- | -- | -- | --
resolve-empty-array : before | 28,337 | 20,586 | 28,921 | 24,328 | 24,328 | 25,300
resolve-empty-array: after | 28,521 | 23,573 | 24,739 | 23,207 | 25,225 | 25,053
resolve-statically: before | 27,890 | 26,767 | 26,627 | 26,576 | 26,783 | 26,928.6
resolve-statically: after | 29,911 | 25,449 | 21,390 | 26,315 | 32,903 | 27,193.6
then: before | 34,278 | 24,873 | 28,511 | 24,134 | 25,575 | 27,474.2
then: after | 31,375 | 23,472 | 26,477 | 25,962 | 25,893 | 26,635.8

promise: function `promise.then` need to be binded

---

deps/jerry/jerry-core/api/jerry.c
deps/jerry/tests/unit-core/test-api.c

'jerry_get_object_keys' always gave back an empty array.
Picked from https://github.com/pando-project/jerryscript/pulls/2807

jerry: Fixed 'jerry_get_object_keys' API function.

---

deps/jerry/jerry-core/profiler/heap-profiler.c
test/run_pass/test_profiler.js

Fixes: https://github.com/yodaos-project/ShadowNode/issues/531

profiler: fix assertion on edge with symbol name

---

src/js/iotjs.js
test/run_pass/test_signal_handler_fail.js
test/testsets.json

This keeps consistent with Node.js' behavior, it uses uv's exception instead of ignoring for this case.

process: use uv's exception if starting an invalid signal handler

---

src/js/stream_writable.js
test/run_pass/test_stream.js

Add this check https://github.com/nodejs/node/blob/master/lib/_stream_writable.js#L299-L300 at ShadowNode, to reproduce the problem, try the following script:
```js
require('fs').createWriteStream('./test').write('foobar')
```

stream: use empty function if no callback with `write()`

---

deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-json.c
test/run_pass/test_iotjs_json.js

This reverts commit 2deca2ee61c6b2a987438ae53d3046254c54d522.
According to [RFC7159](https://tools.ietf.org/html/rfc7159#section-7), all Unicode characters may be placed within the quotation marks, except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters. Any characters may be escaped, but it should be kept as minimal and clear.
With the consensus of above,  characters except for quotation mark, reverse solidus, and the control characters should not be escaped in JSON.stringify.
Fixes: #556 
Refs: #340

Revert "jerry: escape slash in JSON.stringify() (#340)"
